import {
  BarChart3,
  Banknote,
  Blocks,
  BrainCircuit,
  Building2,
  Clapperboard,
  Cloud,
  Database,
  Factory,
  FlaskConical,
  GraduationCap,
  HeartPulse,
  Layout,
  PenTool,
  Plane,
  Scale,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sprout,
  Truck,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { MarqueeItem } from '@/components/common/InfiniteMarquee';

export const INDUSTRIES: MarqueeItem[] = [
  { id: 'healthcare', label: 'Healthcare', icon: HeartPulse, accent: 'red' },
  { id: 'education', label: 'Education', icon: GraduationCap, accent: 'blue' },
  { id: 'finance', label: 'Finance & Banking', icon: Banknote, accent: 'amber' },
  { id: 'retail', label: 'Retail & E-commerce', icon: ShoppingBag, accent: 'violet' },
  { id: 'real-estate', label: 'Real Estate', icon: Building2, accent: 'teal' },
  { id: 'logistics', label: 'Logistics & Transport', icon: Truck, accent: 'orange' },
  { id: 'manufacturing', label: 'Manufacturing', icon: Factory, accent: 'indigo' },
  { id: 'agriculture', label: 'Agriculture', icon: Sprout, accent: 'green' },
  { id: 'travel', label: 'Hospitality & Travel', icon: Plane, accent: 'cyan' },
  { id: 'media', label: 'Media & Entertainment', icon: Clapperboard, accent: 'pink' },
  { id: 'government', label: 'Government & Public Sector', icon: Scale, accent: 'lime' },
  { id: 'energy', label: 'Energy & Utilities', icon: Zap, accent: 'rose' },
];

export interface TechGroup {
  id: string;
  category: string;
  icon: LucideIcon;
  accent: string;
  techs: string[];
}

export const TECH_STACK: TechGroup[] = [
  {
    id: 'frontend',
    category: 'Frontend',
    icon: Layout,
    accent: 'blue',
    techs: ['React', 'Next.js', 'TypeScript', 'Vue.js', 'Tailwind CSS', 'Redux'],
  },
  {
    id: 'mobile',
    category: 'Mobile',
    icon: Smartphone,
    accent: 'cyan',
    techs: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Expo'],
  },
  {
    id: 'backend',
    category: 'Backend',
    icon: Server,
    accent: 'green',
    techs: ['Node.js', 'Python', 'Java', 'Go', '.NET', 'PHP'],
  },
  {
    id: 'databases',
    category: 'Databases',
    icon: Database,
    accent: 'amber',
    techs: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'DynamoDB'],
  },
  {
    id: 'cloud-devops',
    category: 'Cloud & DevOps',
    icon: Cloud,
    accent: 'indigo',
    techs: ['AWS', 'Azure', 'Google Cloud', 'Docker', 'Kubernetes', 'GitHub Actions'],
  },
  {
    id: 'ai-ml',
    category: 'AI & ML',
    icon: BrainCircuit,
    accent: 'violet',
    techs: ['TensorFlow', 'PyTorch', 'OpenAI', 'LangChain', 'Computer Vision', 'NLP'],
  },
  {
    id: 'blockchain',
    category: 'Blockchain',
    icon: Blocks,
    accent: 'orange',
    techs: ['Ethereum', 'Solidity', 'Hyperledger', 'Web3.js', 'IPFS'],
  },
  {
    id: 'data',
    category: 'Data Engineering',
    icon: BarChart3,
    accent: 'teal',
    techs: ['Apache Spark', 'Kafka', 'Airflow', 'Power BI', 'Tableau'],
  },
  {
    id: 'iot',
    category: 'IoT',
    icon: Wifi,
    accent: 'rose',
    techs: ['Arduino', 'Raspberry Pi', 'MQTT', 'AWS IoT', 'ESP32'],
  },
  {
    id: 'testing',
    category: 'Testing & QA',
    icon: FlaskConical,
    accent: 'pink',
    techs: ['Jest', 'Cypress', 'Selenium', 'Postman', 'K6'],
  },
  {
    id: 'security',
    category: 'Security & Compliance',
    icon: ShieldCheck,
    accent: 'red',
    techs: ['OWASP', 'Burp Suite', 'Splunk', 'Snyk', 'ZAP Proxy'],
  },
  {
    id: 'design',
    category: 'Design & Prototyping',
    icon: PenTool,
    accent: 'lime',
    techs: ['Figma', 'Framer', 'Sketch', 'Miro', 'Marvel'],
  },
];

/* Tech brand colors (RGB triplets) — used for chip badges & labels */
export const TECH_COLORS: Record<string, string> = {
  React: '59 130 246',
  'Next.js': '148 163 184',
  TypeScript: '49 120 198',
  'Vue.js': '66 184 131',
  'Tailwind CSS': '14 165 233',
  Redux: '118 74 188',
  'React Native': '14 165 233',
  Flutter: '2 86 155',
  Swift: '240 81 56',
  Kotlin: '127 82 255',
  Expo: '148 163 184',
  'Node.js': '34 197 94',
  Python: '55 118 171',
  Java: '240 152 32',
  Go: '0 150 199',
  '.NET': '81 43 212',
  PHP: '119 123 179',
  PostgreSQL: '65 105 225',
  MySQL: '68 113 161',
  MongoDB: '71 162 72',
  Redis: '220 56 45',
  DynamoDB: '64 83 214',
  AWS: '245 158 11',
  Azure: '0 120 212',
  'Google Cloud': '66 133 244',
  Docker: '36 150 237',
  Kubernetes: '50 108 229',
  'GitHub Actions': '148 163 184',
  TensorFlow: '255 111 0',
  PyTorch: '238 76 44',
  OpenAI: '16 163 127',
  LangChain: '20 184 166',
  'Computer Vision': '94 184 255',
  NLP: '155 107 255',
  Ethereum: '98 126 234',
  Solidity: '148 163 184',
  Hyperledger: '37 99 235',
  'Web3.js': '139 92 246',
  IPFS: '20 184 166',
  'Apache Spark': '234 88 12',
  Kafka: '148 163 184',
  Airflow: '2 132 199',
  'Power BI': '234 179 8',
  Tableau: '234 88 12',
  Arduino: '0 151 157',
  'Raspberry Pi': '197 26 74',
  MQTT: '101 84 192',
  'AWS IoT': '245 158 11',
  ESP32: '148 163 184',
  Jest: '194 19 37',
  Cypress: '148 163 184',
  Selenium: '67 176 42',
  Postman: '255 108 55',
  K6: '125 100 255',
  OWASP: '94 184 255',
  'Burp Suite': '255 102 51',
  Splunk: '249 115 22',
  Snyk: '122 108 209',
  'ZAP Proxy': '2 132 199',
  Figma: '242 78 30',
  Framer: '0 85 255',
  Sketch: '247 181 0',
  Miro: '255 208 47',
  Marvel: '94 184 255',
};
