import {
  Blocks,
  BrainCircuit,
  Boxes,
  Cloud,
  Code,
  Cpu,
  Database,
  Layers,
  Megaphone,
  PenTool,
  ReceiptText,
  Search,
  ShieldCheck,
  Smartphone,
  Users,
  Video,
} from 'lucide-react';
import type { SolutionMeta } from '@/types';

export const SOLUTIONS: SolutionMeta[] = [
  {
    slug: 'web-development',
    name: 'Web Development',
    tagline: 'High-performance web applications',
    description:
      'Modern, scalable web applications built with React, TypeScript and best-in-class tooling — engineered for speed, security and growth.',
    icon: Code,
    accent: 'blue',
    points: [
      'React & Next.js builds',
      'Scalable architecture',
      'SEO & performance',
      'CMS & commerce integration',
      'API-first development',
      'Automated testing & CI/CD',
    ],
    stats: [
      { value: '120+', label: 'Web platforms shipped' },
      { value: '99.9%', label: 'Uptime SLA' },
      { value: '2.4x', label: 'Faster page loads' },
    ],
    techStack: ['React', 'Next.js', 'TypeScript', 'Node.js', 'AWS'],
    industries: [
      'Retail & E-commerce',
      'Finance & Banking',
      'Healthcare',
      'Education',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'mobile-development',
    name: 'Mobile Development',
    tagline: 'Native-quality mobile experiences',
    description:
      'Cross-platform mobile apps with smooth, native-feeling interactions and reliable offline support — from MVP to global scale.',
    icon: Smartphone,
    accent: 'cyan',
    points: [
      'iOS & Android apps',
      'React Native & Flutter',
      'Offline-first experiences',
      'App store publishing',
      'Push notifications & analytics',
      'Biometric authentication',
    ],
    stats: [
      { value: '50+', label: 'Apps delivered' },
      { value: '4.8', label: 'Average store rating' },
      { value: '1M+', label: 'Users reached' },
    ],
    techStack: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase'],
    industries: [
      'Retail & E-commerce',
      'Healthcare',
      'Hospitality & Travel',
      'Logistics & Transport',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    tagline: 'Interfaces people love',
    description:
      'Research-driven product design, design systems and accessible interfaces that convert — clarity in every pixel and interaction.',
    icon: PenTool,
    accent: 'pink',
    points: [
      'User research & personas',
      'Design systems',
      'Prototyping & testing',
      'Accessibility & usability',
      'Motion & interaction design',
      'Design handoff & QA',
    ],
    stats: [
      { value: '200+', label: 'Interfaces designed' },
      { value: '98%', label: 'Client satisfaction' },
      { value: '3x', label: 'Conversion lift' },
    ],
    techStack: ['Figma', 'Framer', 'Sketch', 'ProtoPie', 'Zeplin'],
    industries: [
      'Retail & E-commerce',
      'Healthcare',
      'Finance & Banking',
      'Education',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'ai-machine-learning',
    name: 'AI & Machine Learning',
    tagline: 'Intelligence that scales',
    description:
      'Custom AI models, LLM-powered products and intelligent automation that turn your data into decisions — responsibly and at scale.',
    icon: BrainCircuit,
    accent: 'violet',
    points: [
      'Custom AI model training',
      'NLP & computer vision',
      'Predictive analytics',
      'LLM-powered applications',
      'MLOps & model monitoring',
      'Responsible AI & bias audit',
    ],
    stats: [
      { value: '60+', label: 'Models in production' },
      { value: '92%', label: 'Average model accuracy' },
      { value: '10x', label: 'Faster decisions' },
    ],
    techStack: ['Python', 'PyTorch', 'TensorFlow', 'OpenAI', 'Hugging Face'],
    industries: [
      'Healthcare',
      'Finance & Banking',
      'Manufacturing',
      'Energy & Utilities',
      'Government & Public Sector',
    ],
  },
  {
    slug: 'blockchain-development',
    name: 'Blockchain Development',
    tagline: 'Trust through decentralization',
    description:
      'Smart contracts, dApps and Web3 infrastructure engineered for security, transparency and scale — built on battle-tested chains.',
    icon: Blocks,
    accent: 'orange',
    points: [
      'Smart contract development',
      'dApps & Web3 integration',
      'Tokenization & DeFi',
      'NFT platforms & wallets',
      'Cross-chain bridges',
      'Security audits & formal verification',
    ],
    stats: [
      { value: '40+', label: 'Contracts audited' },
      { value: '$25M+', label: 'Value secured' },
      { value: '100%', label: 'Audit pass rate' },
    ],
    techStack: ['Solidity', 'Ethereum', 'Hardhat', 'Web3.js', 'Chainlink'],
    industries: [
      'Finance & Banking',
      'Real Estate',
      'Government & Public Sector',
      'Logistics & Transport',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'cybersecurity',
    name: 'Cybersecurity',
    tagline: 'Defend, detect, comply',
    description:
      'Security audits, threat monitoring and compliance frameworks that protect your business end to end — proactive, not reactive.',
    icon: ShieldCheck,
    accent: 'red',
    points: [
      'Security audits & pentesting',
      'Threat monitoring',
      'Compliance & governance',
      'Incident response',
      'Red team exercises',
      'Zero-trust architecture',
    ],
    stats: [
      { value: '150+', label: 'Audits completed' },
      { value: '0', label: 'Breaches post-launch' },
      { value: '24/7', label: 'Monitoring coverage' },
    ],
    techStack: ['OWASP', 'Burp Suite', 'Nessus', 'Splunk', 'SOC 2'],
    industries: [
      'Finance & Banking',
      'Healthcare',
      'Government & Public Sector',
      'Energy & Utilities',
      'Retail & E-commerce',
    ],
  },
  {
    slug: 'iot-development',
    name: 'IoT Solutions',
    tagline: 'Connect everything that matters',
    description:
      'End-to-end IoT platforms — from device firmware and connectivity to real-time dashboards and edge analytics.',
    icon: Cpu,
    accent: 'green',
    points: [
      'Device & sensor integration',
      'Real-time dashboards',
      'Edge computing',
      'Remote monitoring',
      'OTA firmware updates',
      'Digital twin modeling',
    ],
    stats: [
      { value: '10K+', label: 'Devices connected' },
      { value: '15ms', label: 'Edge latency' },
      { value: '99.9%', label: 'Platform uptime' },
    ],
    techStack: ['MQTT', 'ESP32', 'AWS IoT', 'InfluxDB', 'Grafana'],
    industries: [
      'Manufacturing',
      'Agriculture',
      'Energy & Utilities',
      'Logistics & Transport',
      'Healthcare',
    ],
  },
  {
    slug: 'data-engineering',
    name: 'Data Engineering',
    tagline: 'Data that drives decisions',
    description:
      'Robust pipelines, warehouses and analytics platforms that transform raw data into actionable intelligence — trusted by the numbers.',
    icon: Database,
    accent: 'indigo',
    points: [
      'Data pipelines & ETL',
      'Data warehousing',
      'Real-time streaming',
      'Analytics dashboards',
      'Data quality & governance',
      'ML feature stores',
    ],
    stats: [
      { value: '20TB+', label: 'Processed daily' },
      { value: '99.5%', label: 'Pipeline reliability' },
      { value: '3x', label: 'Faster insights' },
    ],
    techStack: ['Python', 'Spark', 'Airflow', 'Snowflake', 'dbt'],
    industries: [
      'Finance & Banking',
      'Retail & E-commerce',
      'Healthcare',
      'Manufacturing',
      'Logistics & Transport',
    ],
  },
  {
    slug: 'custom-software',
    name: 'Custom Software',
    tagline: 'Built exactly for you',
    description:
      'Bespoke platforms, enterprise integrations and legacy modernization tailored to your workflows — software that fits, not the reverse.',
    icon: Boxes,
    accent: 'amber',
    points: [
      'Bespoke platform builds',
      'Enterprise integrations',
      'Legacy modernization',
      'Cloud migration',
      'API gateway & microservices',
      'DevOps & platform engineering',
    ],
    stats: [
      { value: '80+', label: 'Platforms delivered' },
      { value: '5x', label: 'Operational efficiency' },
      { value: '100%', label: 'On-time delivery' },
    ],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'Kubernetes'],
    industries: [
      'Manufacturing',
      'Logistics & Transport',
      'Government & Public Sector',
      'Finance & Banking',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'pos-applications',
    name: 'POS Applications',
    tagline: 'Retail at the speed of light',
    description:
      'Modern point-of-sale systems with inventory, billing and analytics — online and offline, anywhere, without missing a sale.',
    icon: ReceiptText,
    accent: 'violet',
    points: [
      'Billing & invoicing',
      'Inventory management',
      'Multi-outlet support',
      'Offline & cloud sync',
      'Customer loyalty & CRM',
      'Analytics & revenue insights',
    ],
    stats: [
      { value: '15K+', label: 'Daily transactions' },
      { value: '2s', label: 'Average checkout' },
      { value: '99.9%', label: 'Offline reliability' },
    ],
    techStack: ['React Native', 'Node.js', 'Redis', 'PostgreSQL', 'Stripe'],
    industries: [
      'Retail & E-commerce',
      'Hospitality & Travel',
      'Real Estate',
      'Finance & Banking',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'saas-platform-development',
    name: 'SaaS Platform Development',
    tagline: 'Multi-tenant products built to scale',
    description:
      'End-to-end SaaS platforms — subscription billing, multi-tenancy and usage analytics built in from day one — engineered to grow with every new customer.',
    icon: Cloud,
    accent: 'teal',
    points: [
      'Multi-tenant architecture',
      'Subscription & billing engine',
      'Usage-based metering',
      'Role-based access control',
      'Self-serve onboarding',
      'Horizontal auto-scaling',
    ],
    stats: [
      { value: '70+', label: 'SaaS products launched' },
      { value: '99.9%', label: 'Platform uptime' },
      { value: '4x', label: 'Faster time-to-market' },
    ],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Stripe', 'AWS'],
    industries: [
      'Retail & E-commerce',
      'Finance & Banking',
      'Healthcare',
      'Education',
      'Manufacturing',
    ],
  },
  {
    slug: 'digital-marketing-branding',
    name: 'Digital Marketing & Branding',
    tagline: 'Brands that stand out and convert',
    description:
      'Brand strategy, campaign design and performance marketing that build recognition and turn audiences into customers — across every channel that matters.',
    icon: Megaphone,
    accent: 'orange',
    points: [
      'Brand identity & guidelines',
      'Social & paid campaigns',
      'Marketing automation',
      'Conversion rate optimization',
      'Email & lifecycle marketing',
      'Analytics & reporting',
    ],
    stats: [
      { value: '300+', label: 'Campaigns launched' },
      { value: '3.5x', label: 'Average ROAS' },
      { value: '40%', label: 'Lift in brand recall' },
    ],
    techStack: ['HubSpot', 'Meta Ads', 'Google Ads', 'Mailchimp', 'GA4'],
    industries: [
      'Retail & E-commerce',
      'Hospitality & Travel',
      'Media & Entertainment',
      'Real Estate',
      'Education',
    ],
  },
  {
    slug: 'seo-optimization',
    name: 'SEO Optimization',
    tagline: 'Get found, get chosen',
    description:
      'Technical SEO, content strategy and link building that lift organic rankings and keep your platform visible to the customers already searching for you.',
    icon: Search,
    accent: 'green',
    points: [
      'Technical SEO audits',
      'On-page & content optimization',
      'Link building & authority',
      'Local & international SEO',
      'Core Web Vitals tuning',
      'Keyword & competitor research',
    ],
    stats: [
      { value: '85%', label: 'Avg. organic traffic growth' },
      { value: '200+', label: 'Keywords ranked page 1' },
      { value: '6mo', label: 'Avg. time to results' },
    ],
    techStack: ['Ahrefs', 'Semrush', 'Search Console', 'Screaming Frog', 'GA4'],
    industries: [
      'Retail & E-commerce',
      'Real Estate',
      'Healthcare',
      'Education',
      'Media & Entertainment',
    ],
  },
  {
    slug: 'content-creation',
    name: 'Content Creation',
    tagline: 'Stories that move audiences',
    description:
      'Video, copy and visual content produced end-to-end — planned, shot, edited and published to keep every channel consistent and on-brand.',
    icon: Video,
    accent: 'pink',
    points: [
      'Video production & editing',
      'Copywriting & scripting',
      'Social content calendars',
      'Graphic & motion design',
      'Podcast & audio production',
      'Content performance tracking',
    ],
    stats: [
      { value: '1500+', label: 'Assets produced' },
      { value: '25M+', label: 'Views generated' },
      { value: '2x', label: 'Engagement lift' },
    ],
    techStack: ['Premiere Pro', 'After Effects', 'Figma', 'Canva', 'Notion'],
    industries: [
      'Media & Entertainment',
      'Retail & E-commerce',
      'Hospitality & Travel',
      'Education',
      'Real Estate',
    ],
  },
  {
    slug: 'erp-systems',
    name: 'ERP Systems',
    tagline: 'One system, every department',
    description:
      'Custom ERP platforms that unify finance, inventory, HR and operations into a single source of truth — replacing spreadsheets with real-time visibility.',
    icon: Layers,
    accent: 'indigo',
    points: [
      'Finance & accounting modules',
      'Inventory & supply chain',
      'HR & payroll management',
      'Procurement & vendor management',
      'Custom workflow automation',
      'Role-based dashboards',
    ],
    stats: [
      { value: '45+', label: 'ERP rollouts' },
      { value: '60%', label: 'Reduction in manual work' },
      { value: '100%', label: 'Data visibility' },
    ],
    techStack: ['Node.js', 'PostgreSQL', 'React', 'Docker', 'Kubernetes'],
    industries: [
      'Manufacturing',
      'Logistics & Transport',
      'Retail & E-commerce',
      'Agriculture',
      'Government & Public Sector',
    ],
  },
  {
    slug: 'lms-crm-solutions',
    name: 'LMS & CRM Solutions',
    tagline: 'Manage learners and relationships in one place',
    description:
      'Learning management and customer relationship platforms that track progress, automate follow-ups and keep every interaction organized and actionable.',
    icon: Users,
    accent: 'blue',
    points: [
      'Course & content management',
      'Learner progress tracking',
      'Sales pipeline & lead scoring',
      'Automated follow-ups',
      'Custom reporting dashboards',
      'Third-party integrations',
    ],
    stats: [
      { value: '90+', label: 'LMS/CRM deployments' },
      { value: '2M+', label: 'Learners & contacts managed' },
      { value: '35%', label: 'Faster follow-up times' },
    ],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Twilio', 'SendGrid'],
    industries: [
      'Education',
      'Finance & Banking',
      'Healthcare',
      'Real Estate',
      'Retail & E-commerce',
    ],
  },
];
