import {
  Blocks,
  BrainCircuit,
  Boxes,
  Code,
  Cpu,
  Database,
  PenTool,
  ReceiptText,
  ShieldCheck,
  Smartphone,
} from 'lucide-react';
import type { SolutionMeta } from '@/types';

export const SOLUTIONS: SolutionMeta[] = [
  {
    slug: 'web-development',
    name: 'Web Development',
    tagline: 'High-performance web applications',
    description:
      'Modern, scalable web applications built with React, TypeScript and best-in-class tooling — engineered for speed, security and growth.',
    icon: Code,
    accent: 'blue',
    points: [
      'React & Next.js builds',
      'Scalable architecture',
      'SEO & performance',
      'CMS & commerce integration',
      'API-first development',
      'Automated testing & CI/CD',
    ],
    stats: [
      { value: '120+', label: 'Web platforms shipped' },
      { value: '99.9%', label: 'Uptime SLA' },
      { value: '2.4x', label: 'Faster page loads' },
    ],
    techStack: ['React', 'Next.js', 'TypeScript', 'Node.js', 'AWS'],
  },
  {
    slug: 'mobile-development',
    name: 'Mobile Development',
    tagline: 'Native-quality mobile experiences',
    description:
      'Cross-platform mobile apps with smooth, native-feeling interactions and reliable offline support — from MVP to global scale.',
    icon: Smartphone,
    accent: 'cyan',
    points: [
      'iOS & Android apps',
      'React Native & Flutter',
      'Offline-first experiences',
      'App store publishing',
      'Push notifications & analytics',
      'Biometric authentication',
    ],
    stats: [
      { value: '50+', label: 'Apps delivered' },
      { value: '4.8', label: 'Average store rating' },
      { value: '1M+', label: 'Users reached' },
    ],
    techStack: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase'],
  },
  {
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    tagline: 'Interfaces people love',
    description:
      'Research-driven product design, design systems and accessible interfaces that convert — clarity in every pixel and interaction.',
    icon: PenTool,
    accent: 'pink',
    points: [
      'User research & personas',
      'Design systems',
      'Prototyping & testing',
      'Accessibility & usability',
      'Motion & interaction design',
      'Design handoff & QA',
    ],
    stats: [
      { value: '200+', label: 'Interfaces designed' },
      { value: '98%', label: 'Client satisfaction' },
      { value: '3x', label: 'Conversion lift' },
    ],
    techStack: ['Figma', 'Framer', 'Sketch', 'ProtoPie', 'Zeplin'],
  },
  {
    slug: 'ai-machine-learning',
    name: 'AI & Machine Learning',
    tagline: 'Intelligence that scales',
    description:
      'Custom AI models, LLM-powered products and intelligent automation that turn your data into decisions — responsibly and at scale.',
    icon: BrainCircuit,
    accent: 'violet',
    points: [
      'Custom AI model training',
      'NLP & computer vision',
      'Predictive analytics',
      'LLM-powered applications',
      'MLOps & model monitoring',
      'Responsible AI & bias audit',
    ],
    stats: [
      { value: '60+', label: 'Models in production' },
      { value: '92%', label: 'Average model accuracy' },
      { value: '10x', label: 'Faster decisions' },
    ],
    techStack: ['Python', 'PyTorch', 'TensorFlow', 'OpenAI', 'Hugging Face'],
  },
  {
    slug: 'blockchain-development',
    name: 'Blockchain Development',
    tagline: 'Trust through decentralization',
    description:
      'Smart contracts, dApps and Web3 infrastructure engineered for security, transparency and scale — built on battle-tested chains.',
    icon: Blocks,
    accent: 'orange',
    points: [
      'Smart contract development',
      'dApps & Web3 integration',
      'Tokenization & DeFi',
      'NFT platforms & wallets',
      'Cross-chain bridges',
      'Security audits & formal verification',
    ],
    stats: [
      { value: '40+', label: 'Contracts audited' },
      { value: '$25M+', label: 'Value secured' },
      { value: '100%', label: 'Audit pass rate' },
    ],
    techStack: ['Solidity', 'Ethereum', 'Hardhat', 'Web3.js', 'Chainlink'],
  },
  {
    slug: 'cybersecurity',
    name: 'Cybersecurity',
    tagline: 'Defend, detect, comply',
    description:
      'Security audits, threat monitoring and compliance frameworks that protect your business end to end — proactive, not reactive.',
    icon: ShieldCheck,
    accent: 'red',
    points: [
      'Security audits & pentesting',
      'Threat monitoring',
      'Compliance & governance',
      'Incident response',
      'Red team exercises',
      'Zero-trust architecture',
    ],
    stats: [
      { value: '150+', label: 'Audits completed' },
      { value: '0', label: 'Breaches post-launch' },
      { value: '24/7', label: 'Monitoring coverage' },
    ],
    techStack: ['OWASP', 'Burp Suite', 'Nessus', 'Splunk', 'SOC 2'],
  },
  {
    slug: 'iot-development',
    name: 'IoT Solutions',
    tagline: 'Connect everything that matters',
    description:
      'End-to-end IoT platforms — from device firmware and connectivity to real-time dashboards and edge analytics.',
    icon: Cpu,
    accent: 'green',
    points: [
      'Device & sensor integration',
      'Real-time dashboards',
      'Edge computing',
      'Remote monitoring',
      'OTA firmware updates',
      'Digital twin modeling',
    ],
    stats: [
      { value: '10K+', label: 'Devices connected' },
      { value: '15ms', label: 'Edge latency' },
      { value: '99.9%', label: 'Platform uptime' },
    ],
    techStack: ['MQTT', 'ESP32', 'AWS IoT', 'InfluxDB', 'Grafana'],
  },
  {
    slug: 'data-engineering',
    name: 'Data Engineering',
    tagline: 'Data that drives decisions',
    description:
      'Robust pipelines, warehouses and analytics platforms that transform raw data into actionable intelligence — trusted by the numbers.',
    icon: Database,
    accent: 'indigo',
    points: [
      'Data pipelines & ETL',
      'Data warehousing',
      'Real-time streaming',
      'Analytics dashboards',
      'Data quality & governance',
      'ML feature stores',
    ],
    stats: [
      { value: '20TB+', label: 'Processed daily' },
      { value: '99.5%', label: 'Pipeline reliability' },
      { value: '3x', label: 'Faster insights' },
    ],
    techStack: ['Python', 'Spark', 'Airflow', 'Snowflake', 'dbt'],
  },
  {
    slug: 'custom-software',
    name: 'Custom Software',
    tagline: 'Built exactly for you',
    description:
      'Bespoke platforms, enterprise integrations and legacy modernization tailored to your workflows — software that fits, not the reverse.',
    icon: Boxes,
    accent: 'amber',
    points: [
      'Bespoke platform builds',
      'Enterprise integrations',
      'Legacy modernization',
      'Cloud migration',
      'API gateway & microservices',
      'DevOps & platform engineering',
    ],
    stats: [
      { value: '80+', label: 'Platforms delivered' },
      { value: '5x', label: 'Operational efficiency' },
      { value: '100%', label: 'On-time delivery' },
    ],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'Kubernetes'],
  },
  {
    slug: 'pos-applications',
    name: 'POS Applications',
    tagline: 'Retail at the speed of light',
    description:
      'Modern point-of-sale systems with inventory, billing and analytics — online and offline, anywhere, without missing a sale.',
    icon: ReceiptText,
    accent: 'violet',
    points: [
      'Billing & invoicing',
      'Inventory management',
      'Multi-outlet support',
      'Offline & cloud sync',
      'Customer loyalty & CRM',
      'Analytics & revenue insights',
    ],
    stats: [
      { value: '15K+', label: 'Daily transactions' },
      { value: '2s', label: 'Average checkout' },
      { value: '99.9%', label: 'Offline reliability' },
    ],
    techStack: ['React Native', 'Node.js', 'Redis', 'PostgreSQL', 'Stripe'],
  },
];
